// <auto-generated />
namespace Restaurant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixCategoryItemRelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixCategoryItemRelation));
        
        string IMigrationMetadata.Id
        {
            get { return "202112301327548_Fix-Category-Item-Relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
